### ISSUE TITLE
ajustes en funcion Buscar_partido()

### ISSUE THREAD

**Issue by fede-cordoba-Ispc** [eliasvalentinb/proyecto_grupo21#2]
@eliasvalentinb ajustas en el condigo, para que al ejecutar el cursor que ejecuta el select a la tabla partidos nos muestre solo los que tengan faltante de jugadores y cuya fecha sea mayor o igual al día en curso.
después reemplazar el anterior. gracias.

**Comment by eliasvalentinb** [comment]
listo
